### ISSUE TITLE
Remove node_modules from GitHubs

### ISSUE THREAD

**Issue by pdehaan** [RichardLitt/journall#3]
Looks like "node_modules" is already in .gitignore, but maybe the folder was checked in before that: https://github.com/RichardLitt/journall/tree/master/node_modules

**Comment by RichardLitt** [comment]
Removed. Landed on 2.0.3.

**Comment by pdehaan** [comment]
![](http://www.pipefy.com/wp-content/uploads/2016/05/go-teamwork.gif)

**Comment by RichardLitt** [comment]
Rob Lowe is my favorite person ever.
